# KNN — The Library Version

Same model in scikit-learn, verifying the scratch build. sklearn adds speed tricks (KD-trees / ball trees so prediction doesn't scan every point — README §6's fix) but the algorithm is identical: memorize, measure, vote.

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv("data/fruit_data.csv")
X = df[["weight_g", "sweetness_brix"]].values
y = df["fruit"].values

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2, random_state=11)   # Block 6
scaler = StandardScaler().fit(Xtr)              # fit on TRAIN only — the sealed exam (README §9)
Xtr_s, Xte_s = scaler.transform(Xtr), scaler.transform(Xte)

model = KNeighborsClassifier(n_neighbors=5)     # our K
model.fit(Xtr_s, ytr)                           # 'fit' = memorize. Finishes instantly (README §3.3)

pred = model.predict(Xte_s)
print(f"Test accuracy: {accuracy_score(yte, pred):.0%}   ← same ballpark as the scratch build")
print("\nConfusion matrix (lemon/apple/orange):\n", confusion_matrix(yte, pred, labels=["lemon","apple","orange"]))

Test accuracy: 92%   ← same ballpark as the scratch build

Confusion matrix (lemon/apple/orange):
 [[13  0  0]
 [ 0 13  1]
 [ 0  2  7]]


**The takeaway:** `KNeighborsClassifier` is Blocks 4–6 with industrial neighbor-search structures bolted on. The `.fit()` that returns instantly is the tell — nothing is being learned, only stored (README §3.3).